apiVersion: apps/v1
kind: Deployment
metadata:
  name: zfsreplication-controller
  namespace: zfsreplication-system
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --watch-namespace=$(WATCH_NAMESPACE)
          env:
            - name: WATCH_NAMESPACE
              value: zfsreplication-smoke
