apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zfsreplication-controller-receiver-pod-reader
  namespace: zfsreplication-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
