apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zfs-receiver
  namespace: zfsreplication-smoke
rules:
  - apiGroups:
      - zfsreplication.ringhof.io
    resources:
      - zfsreceivetasks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zfsreplication.ringhof.io
    resources:
      - zfsreceivetasks/status
    verbs:
      - get
      - update
      - patch
