apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zfsreplication-controller
rules:
  - apiGroups:
      - zfsreplication.example.com
    resources:
      - zfsreplications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zfsreplication.example.com
    resources:
      - zfsreplications/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
