resources:
  - manager/namespace.yaml
  - crd/zfsreplication.ringhof.io_zfsreceivetasks.yaml
  - crd/zfsreplication.ringhof.io_zfsreplicationruns.yaml
  - crd/zfsreplication.ringhof.io_zfsreplicationschedules.yaml
  - rbac/service_account.yaml
  - rbac/receiver_service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - rbac/receiver_role.yaml
  - rbac/receiver_role_binding.yaml
  - manager/deployment.yaml
  - receiver/daemonset.yaml
