resources:
  - manager/namespace.yaml
  - crd/zfsreplication.example.com_zfsreplicationruns.yaml
  - crd/zfsreplication.example.com_zfsreplicationschedules.yaml
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - manager/deployment.yaml
